### PR TITLE
Fixed your issue with the hyperlinks

### PR DESCRIPTION
**Pull request by AaryanKhClasses**
@SpiderMath hehehe

### CODE REVIEW

**Comment by AaryanKhClasses** [comment]
Bruh merge it fast @SpiderMath

**Comment by AaryanKhClasses** [comment]
JUST MERGE THE PR ALREADY BRUH @SpiderMath

**Comment by AaryanKhClasses** [comment]
Merge it already bruh. It's been 20 hours :/ 😠

**Comment by AaryanKhClasses** [comment]
:rage:

**Comment by SpiderMath** [comment]
I'm lazy

**Comment by SpiderMath** [comment]
Can you do it for me?

**Comment by SpiderMath** [comment]
Nevermind, I'll do it myself I guess

**Comment by AaryanKhClasses** [comment]
....

**Comment by AaryanKhClasses** [comment]
k gud

**Comment by SpiderMath** [comment]
Hmmm

**Comment by SpiderMath** [comment]
Is it actually good?

**Comment by SpiderMath** [comment]
Doubt it :thinking:

**Pull request merged**
